# Numpy Tutorial

In [1]:
import numpy as np

In [41]:
a = np.array([[1,2,3], 
              [4,5,6]], dtype="int16")

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [34]:
# Dimension of array
a.ndim

2

In [35]:
# Shape of the array mxn
a.shape

(2, 3)

In [36]:
# No. of elements in the matrix
a.size

6

In [37]:
a.dtype

dtype('int16')

In [38]:
# size of each element of the array in memory in bytes
a.itemsize

2

In [39]:
a.data

# Complex Array

In [48]:
c = np.array([[1,2,3],
             [3,4,5]], dtype="complex")
print(c)

[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


# Placeholder elements

In [51]:
print(np.zeros((2,3))) # Array of size 2x3. all elements zeros
print(np.ones((1,3))) # Array of size 1x3, all elements ones

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]]


# Arange Function

In [71]:
# similar to range function in python
# np.arange(start, end(excluding), ...steps)
print(np.arange(1, 10, 2))
print(np.arange(1, 10, 0.5)) # also accepts floats
print(np.arange(10)) # values from 0 to 10

[1 3 5 7 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[0 1 2 3 4 5 6 7 8 9]


In [62]:
'''
When arange is used with floating point arguments, it is generally not 
possible to predict the number of elements obtained, due to the finite 
floating point precision. For this reason, it is usually better to use 
the function linspace that receives as an argument the number of 
elements that we want, instead of the step:
'''

print(np.linspace(0,3,10)) # 10 numbers from 0 to 3


[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [69]:
from numpy import pi
x = np.linspace(0, pi/2 , 4)

print(np.sin(x)) # Four values of sin(x) from x=0 to x=pi/2

[0.        0.5       0.8660254 1.       ]
